### ISSUE TITLE
Setup Does not work

### ISSUE THREAD

**Issue by NicolasHumann** [ololiuhqui/magnolia-free-hugo-theme#2]
Hello,

I floow your setup instruction but:

\_default\baseof.html:2:76": execute of template failed: template: pages/contacts.html:2:76: executing "pages/contacts.html" at <partialCached "func/GetLanguageDirection" "GetLanguageDirection">: error calling partialCached: partial "func/GetLanguageDirection" not found

\themes\Magnolia\layouts\_default\baseof.html:3:6": execute of template failed: template: pages/office.html:3:6: executing "pages/office.html" at <partial "head.html" .>: error calling partial: execute of template failed: html/template:partials/head.html:56:14: no such template "_internal/google_analytics_async.html"

Thank you for your help

**Comment by nikhar-savaliya** [comment]
go to /themes/Magnolia/layouts/partials/head.html
remove this line(line number 56) {{ template "_internal/google_analytics_async.html" . }}

worked for me

**Comment by NicolasHumann** [comment]
Thank you but I have this error alos:

 \layouts\_default\baseof.html:2:76": execute of template failed: template: pages/404.html:2:76: executing "pages/404.html" at <partialCached "func/GetLanguageDirection" "GetLanguageDirection">: error calling partialCached: partial "func/GetLanguageDirection" not found

\layouts\_default\baseof.html:2:76": execute of template failed: template: _index.html:2:76: executing "_index.html" at <partialCached "func/GetLanguageDirection" "GetLanguageDirection">: error calling partialCached: partial "func/GetLanguageDirection" not found
